const swaggerJsdoc = require('swagger-jsdoc');
const swaggerUi = require('swagger-ui-express');

// Swagger set up
const options = {
  swaggerDefinition: {
    swagger: "2.0",
    info: {
      title: 'Test API',
      version: '1.0.0',
      description: 'Test Express API with autogenerated swagger doc',
    },
    consumes: "application/json",
    contact: {
      "email": "victor.depta@outlook.com"
    },    
    basePath: "/",
    servers: [
      {
        url: "http://localhost:3000/"
      }
    ]
  },
  apis: ['initializeEndpoints.js'],
};
const specs = swaggerJsdoc(options);

module.exports = (app) => {
 app.use('/api-docs', swaggerUi.serve, swaggerUi.setup(specs))
}